# TODO:
# - look into a zero-downtime sort of strategy
# - consider keter or similar with a CI => /opt/keter/incoming push
---
- hosts: pibase
  remote_user: ubuntu
  tasks:
    - name: Start mainentance mode
      become: true
      become_user: pibase
      file:
        path: /app/maintenance.on
        state: touch
    - name: Stop service
      become: true
      service:
        name: pi-base
        state: stopped
    - name: Pull binary
      become: true
      become_user: pibase
      raw:
        aws s3 cp s3://pi-base/deploy/server/pibase /app/server/pibase
    - name: Restart service
      become: true
      service:
        name: pi-base
        state: started
    - name: Stop mainentance mode
      become: true
      become_user: pibase
      file:
        path: /app/maintenance.on
        state: absent
